const DATA_URL='data/data.json';
let DATA=null,currentPerson='Elise',currentRange='YTD',fxRange='YTD',companyMetric='revenue',showSP=false;
const $=id=>document.getElementById(id),N=n=>Number(n),valid=n=>Number.isFinite(N(n));
const nok=n=>valid(n)?new Intl.NumberFormat('nb-NO',{style:'currency',currency:'NOK',maximumFractionDigits:0}).format(N(n)):'–';
const num=(n,d=2)=>valid(n)?new Intl.NumberFormat('nb-NO',{minimumFractionDigits:d,maximumFractionDigits:d}).format(N(n)):'–';
const pct=n=>valid(n)?new Intl.NumberFormat('nb-NO',{style:'percent',minimumFractionDigits:1,maximumFractionDigits:1,signDisplay:'exceptZero'}).format(N(n)):'–';
const sharePct=n=>valid(n)?new Intl.NumberFormat('nb-NO',{style:'percent',minimumFractionDigits:1,maximumFractionDigits:1}).format(N(n)):'–';
const billionUSD=n=>valid(n)?'$'+num(N(n)/1000,1)+' milliarder':'–';

async function init(){
  try{const r=await fetch(DATA_URL+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Kunne ikke hente data.json');DATA=await r.json();bindUI();render();$('loading').classList.add('hidden')}
  catch(e){$('loading').innerHTML=`<strong>Kunne ikke hente data</strong><span>${e.message}</span>`}
}
function bindUI(){
  document.querySelectorAll('.profile').forEach(b=>b.onclick=()=>{currentPerson=b.dataset.person;document.querySelectorAll('.profile').forEach(x=>x.classList.toggle('active',x===b));render()});
  document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const page=$('page-'+b.dataset.page);if(page)page.classList.add('active');$('pageTitle').textContent=b.dataset.page==='home'?'Min portefølje':b.dataset.page==='stock'?'Aksjen min':'Selskapet';window.scrollTo({top:0,behavior:'smooth'})});
  document.querySelectorAll('.stock-range-tabs button').forEach(b=>b.onclick=()=>{currentRange=b.dataset.range;document.querySelectorAll('.stock-range-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderStockChart()});
  document.querySelectorAll('.fx-range-tabs button').forEach(b=>b.onclick=()=>{fxRange=b.dataset.fxRange;document.querySelectorAll('.fx-range-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderFxChart()});
  document.querySelectorAll('.metric-tabs button').forEach(b=>b.onclick=()=>{companyMetric=b.dataset.metric;document.querySelectorAll('.metric-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderCompanyChart()});
  if($('spToggle'))$('spToggle').onchange=e=>{showSP=e.target.checked;renderStockChart()};
  if($('purchaseDetailToggle'))$('purchaseDetailToggle').onclick=()=>{const d=$('purchaseDetails'),open=d.classList.toggle('open');$('purchaseDetailToggle').textContent=open?'Skjul kjøpsdetaljer':'Vis kjøpsdetaljer'};
}
function render(){
  const p=DATA?.portfolio?.[currentPerson]||{},has=!!p.ticker&&N(p.shares)>0,a=p.allocation||{};
  setText('totalValue',nok(p.totalValueNOK));setText('stockValue',nok(p.stockValueNOK));setText('equityFundValue',nok(p.equityFundValueNOK||0));setText('fixedFundValue',nok(p.fixedIncomeFundValueNOK||0));setText('cashValue',nok(p.cashNOK));
  setText('stockPct',sharePct(a.stockPct));setText('equityFundPct',sharePct(a.equityFundPct||0));setText('fixedFundPct',sharePct(a.fixedIncomeFundPct||0));setText('cashPct',sharePct(a.cashPct));setText('updated','Oppdatert\n'+formatDateTime(DATA?.meta?.updated));renderAllocation(p);renderPortfolioChart(p);
  setReturn('stockReturnHome',p.stockPerformance?.returnPct,p.stockPerformance?'avkastning':'ingen aksje');setReturn('fundReturnHome',p.fundPerformance?.returnPct,p.fundPerformance?'avkastning':'venter på neste måling');
  setText('stockPageTitle',has?(p.company||p.ticker):'Aksjen min');setText('companyPageTitle',has?(p.company||p.ticker):'Forstå selskapet');
  ['stockMainCard','purchaseCard','marketMiniCards','fxCard','reportCard'].forEach(id=>{if($(id))$(id).style.display=has?'block':'none'});if($('marketMiniCards'))$('marketMiniCards').style.display=has?'grid':'none';if($('noStock'))$('noStock').style.display=has?'none':'block';
  renderEarnings();if(has){renderStockChart();renderFxChart();renderPurchase(p);renderCompany()}
}
function setText(id,v){if($(id))$(id).textContent=v}
function renderAllocation(p){const a=p.allocation||{},parts=[['stock',a.stockPct],['equityfund',a.equityFundPct],['fixedfund',a.fixedIncomeFundPct],['cash',a.cashPct]];$('allocationBar').innerHTML=parts.map(x=>`<span class="${x[0]}" style="width:${(N(x[1])||0)*100}%"></span>`).join('')}
function setReturn(id,value,suffix=''){const el=$(id);if(!el)return;el.classList.remove('positive','negative');if(!valid(value)){el.textContent=suffix||'–';return}el.textContent=pct(value)+(suffix?' '+suffix:'');el.classList.add(N(value)>=0?'positive':'negative')}
function renderEarnings(){const d=DATA?.meta?.nextEarningsDate;if(!d){setText('earningsDate','Ikke registrert');setText('earningsCountdown','Rapportdato mangler');return}setText('earningsDate',formatDate(d));const today=new Date();today.setHours(0,0,0,0);const target=new Date(d+'T12:00:00'),days=Math.ceil((target-today)/86400000);setText('earningsCountdown',days>=0?`${days} dager igjen`:'Rapportdato passert')}
function rangedRows(key,range){const hist=(DATA?.market?.history||[]).filter(x=>x.date&&valid(x[key]));if(!hist.length)return[];const end=new Date(hist[hist.length-1].date+'T12:00:00');let cutoff=null;if(range==='1M'){cutoff=new Date(end);cutoff.setMonth(cutoff.getMonth()-1)}if(range==='1Y'){cutoff=new Date(end);cutoff.setFullYear(cutoff.getFullYear()-1)}if(range==='YTD')cutoff=new Date(end.getFullYear(),0,1);return cutoff?hist.filter(x=>new Date(x.date+'T12:00:00')>=cutoff):hist}
function renderStockChart(){const p=DATA?.portfolio?.[currentPerson]||{};if(!p.ticker)return;const rows=rangedRows('mcdUSD',currentRange),latest=DATA?.market?.latest||{};setText('chartPrice','$ '+num(latest.mcdUSD));setText('lastUsd','$ '+num(latest.mcdUSD));setText('fx',num(latest.usdNok,2));const ret=periodChange(rows,'mcdUSD');setReturn('periodReturn',ret);const markers=(DATA?.market?.purchaseMarkers||[]).filter(m=>m.person===currentPerson&&m.ticker===p.ticker&&rows.some(r=>r.date===m.date));if(showSP){drawCompareChart(rows,markers);const sr=periodChange(rows.filter(x=>valid(x.sp500)),'sp500');$('comparisonResult').innerHTML=`<b>MCD ${pct(ret)}</b><span>S&amp;P 500 ${pct(sr)}</span>`;$('stockLegend').innerHTML='<span><i class="line-dot"></i>MCD</span><span><i class="sp-dot"></i>S&amp;P 500</span><span><i class="buy-dot"></i>Mitt kjøp</span>'}else{drawLine('priceChart',rows,'mcdUSD',markers,'chart-line');$('comparisonResult').innerHTML='';$('stockLegend').innerHTML='<span><i class="line-dot"></i>MCD</span><span><i class="buy-dot"></i>Mitt kjøp</span>'}renderMarketChanges()}
function renderFxChart(){const rows=rangedRows('usdNok',fxRange),latest=DATA?.market?.latest||{};setText('fxChartNow',valid(latest.usdNok)?num(latest.usdNok,2)+' kr':'–');const r=periodChange(rows,'usdNok');setReturn('fxPeriodReturn',r);drawLine('fxChart',rows,'usdNok',[],'fx-line')}
function periodChange(rows,key){return rows.length>1&&N(rows[0][key])?N(rows[rows.length-1][key])/N(rows[0][key])-1:null}
function renderMarketChanges(){const h=DATA?.market?.history||[];addChange('lastUsd',changeDays(h,'mcdUSD',1),changeDays(h,'mcdUSD',30));addChange('fx',changeDays(h,'usdNok',1),changeDays(h,'usdNok',30))}
function changeDays(h,key,days){const a=h.filter(x=>x.date&&valid(x[key]));if(a.length<2)return null;const last=a[a.length-1],cut=new Date(last.date+'T12:00:00');cut.setDate(cut.getDate()-days);let first=a[0];for(let i=a.length-1;i>=0;i--){if(new Date(a[i].date+'T12:00:00')<=cut){first=a[i];break}}return N(first[key])?N(last[key])/N(first[key])-1:null}
function addChange(id,day,month){const el=$(id);if(!el)return;const box=el.parentElement;let e=box.querySelector('.market-change');if(!e){e=document.createElement('div');e.className='market-change';box.appendChild(e)}e.innerHTML=`<span class="${N(day)>=0?'positive':'negative'}">${N(day)>=0?'▲':'▼'} ${pct(Math.abs(N(day)))} dag</span><span class="${N(month)>=0?'positive':'negative'}">${N(month)>=0?'▲':'▼'} ${pct(Math.abs(N(month)))} 1 mnd</span>`}
function renderPurchase(p){const perf=p.stockPerformance||{};setReturn('purchaseReturn',perf.returnPct);const gain=$('purchaseGain');gain.textContent=nok(perf.gainNOK);gain.classList.remove('positive','negative');if(valid(perf.gainNOK))gain.classList.add(N(perf.gainNOK)>=0?'positive':'negative');const buys=(DATA?.market?.purchaseMarkers||[]).filter(x=>x.person===currentPerson&&x.ticker===p.ticker);if(!buys.length){$('purchaseDetails').innerHTML='<div class="detail"><span>Kjøp</span><strong>Ingen registrert handel</strong></div>';return}const b=buys[buys.length-1],rows=[['Dato',formatDate(b.date)],['Antall',num(b.shares,0)],['Kjøpskurs','$ '+num(b.priceLocal)],['USD/NOK',num(b.fxNOK,2)],['Kjøpsverdi',nok(b.purchaseValueNOK)],['Gebyr',nok(b.feeNOK)],['Kostpris inkl. gebyr',nok(perf.costNOK)]];$('purchaseDetails').innerHTML=rows.map(r=>`<div class="detail"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join('')}
function renderCompany(){const inc=(DATA?.financials?.incomeMCD||[]).filter(x=>/^Q\d/.test(x.period));if(!inc.length)return;const q=inc[inc.length-1],yearAgo=findYearAgo(inc,q.period);setText('latestQuarter',prettyPeriod(q.period));setText('companyTicker',DATA?.portfolio?.[currentPerson]?.ticker||'MCD');setText('revenue',billionUSD(q.revenue));setPlainDelta('revenueGrowth',q.revenueGrowthYoY,'fra samme kvartal i fjor');setText('opIncome',billionUSD(q.operatingIncome));setPlainDelta('opGrowth',q.operatingIncomeGrowthYoY,'fra samme kvartal i fjor');setText('eps','$'+num(q.eps));setPlainDelta('epsGrowth',q.epsGrowthYoY,'fra samme kvartal i fjor');setText('margin',pct(q.operatingMargin));const md=yearAgo&&valid(yearAgo.operatingMargin)?N(q.operatingMargin)-N(yearAgo.operatingMargin):null;const me=$('marginChange');if(me){me.classList.remove('positive','negative');if(valid(md)){me.textContent=`${num(Math.abs(md)*100,1)} prosentpoeng ${md>=0?'høyere':'lavere'} enn samme kvartal i fjor`;me.classList.add(md>=0?'positive':'negative')}else me.textContent='–'}renderCompanyChart();renderKpi();renderPE()}
function setPlainDelta(id,v,label){const e=$(id);if(!e)return;e.classList.remove('positive','negative');e.textContent=valid(v)?`${N(v)>=0?'↑':'↓'} ${pct(Math.abs(N(v)))} ${label}`:'–';if(valid(v))e.classList.add(N(v)>=0?'positive':'negative')}
function findYearAgo(rows,period){const m=String(period).match(/^Q(\d)\s+(\d{4})$/);if(!m)return null;return rows.find(x=>x.period===`Q${m[1]} ${N(m[2])-1}`)||null}
function prettyPeriod(p){return String(p).replace(/^Q(\d)\s+(\d{4})$/,'Q$1 $2')}
function renderCompanyChart(){const rows=(DATA?.financials?.incomeMCD||[]).filter(x=>/^Q\d/.test(x.period)&&valid(x[companyMetric])).slice(-6);drawBars('companyChart',rows,companyMetric)}
function renderKpi(){const rows=(DATA?.kpi?.mcd||[]).filter(x=>/^Q\d/.test(x.period)),q=rows[rows.length-1]||{};setText('compSales',pct(q.globalComparableSales));setText('usCompSales',pct(q.usComparableSales));setText('loyaltyUsers',valid(q.loyaltyUsersM)?num(q.loyaltyUsersM,0)+' millioner':'–');setText('loyaltySales',valid(q.loyaltySalesTtmBn)?'$'+num(q.loyaltySalesTtmBn,0)+' milliarder':'–')}
function renderPE(){const rows=(DATA?.valuation?.history||[]).filter(x=>valid(x.peTtm)),cur=rows[rows.length-1];setText('currentPE',cur?num(cur.peTtm,1)+'×':'–');drawLine('peChart',rows,'peTtm',[],'chart-line');setText('peStart',rows[0]?formatDate(rows[0].date):'–');setText('peEnd',cur?formatDate(cur.date):'–')}
function renderPortfolioChart(p){const rows=(p.history||[]).filter(x=>x.date&&valid(x.totalValueNOK));const svg=$('portfolioChart');if(!svg)return;if(!rows.length){svg.innerHTML='';setText('portfolioHistoryNote','Historikken starter når første måling er registrert.');return}drawMultiPortfolio(svg,rows);setText('portfolioHistoryNote',rows.length<2?'Første målepunkt er registrert. Kurven blir synlig når neste månedsverdi legges inn.':'Kurvene viser verdi. Flytting av penger mellom plasseringer påvirker derfor også linjene.')}
function drawMultiPortfolio(svg,rows){const w=700,h=280,L=76,R=18,T=22,B=44,keys=[['totalValueNOK','portfolio-total','#332b37'],['stockValueNOK','portfolio-stock','#705878'],['equityFundValueNOK','portfolio-equity','#a57c9c'],['fixedIncomeFundValueNOK','portfolio-fixed','#a99bb4'],['cashNOK','portfolio-cash','#b8afb9']],vals=[];rows.forEach(r=>keys.forEach(k=>{if(valid(r[k[0]]))vals.push(N(r[k[0]]))}));const max=Math.max(...vals,1)*1.08,min=0,rg=max-min,x=i=>rows.length===1?(L+w-R)/2:L+(w-L-R)*i/(rows.length-1),y=v=>T+(h-T-B)*(1-(N(v)-min)/rg);let html='';for(let i=0;i<4;i++){const v=max-rg*i/3,Y=y(v);html+=`<line class="grid-line" x1="${L}" y1="${Y}" x2="${w-R}" y2="${Y}"/><text class="axis-label" text-anchor="end" x="${L-9}" y="${Y+5}">${compactNok(v)}</text>`}keys.forEach(k=>{const pts=rows.filter(r=>valid(r[k[0]])).map((r,i)=>`${x(i)},${y(r[k[0]])}`).join(' ');if(rows.length>1)html+=`<polyline class="${k[1]}" points="${pts}"/>`;rows.forEach((r,i)=>{if(valid(r[k[0]]))html+=`<circle class="portfolio-point" fill="${k[2]}" cx="${x(i)}" cy="${y(r[k[0]])}" r="${k[0]==='totalValueNOK'?5:3}"/>`})});rows.forEach((r,i)=>{if(rows.length<=5||i===0||i===rows.length-1)html+=`<text class="axis-label" text-anchor="${i===0?'start':i===rows.length-1?'end':'middle'}" x="${x(i)}" y="${h-8}">${shortDate(r.date)}</text>`});svg.innerHTML=html}
function compactNok(v){return Math.abs(v)>=1000?num(v/1000,0)+'k':num(v,0)}
function drawCompareChart(rows,markers){const svg=$('priceChart');if(!svg||rows.length<2){if(svg)svg.innerHTML='';return}const baseM=N(rows[0].mcdUSD),sp=rows.filter(x=>valid(x.sp500)),baseS=sp.length?N(sp[0].sp500):null,rr=rows.map(r=>Object.assign({},r,{mcdP:(N(r.mcdUSD)/baseM-1)*100,spP:baseS&&valid(r.sp500)?(N(r.sp500)/baseS-1)*100:null})),vals=[];rr.forEach(r=>{if(valid(r.mcdP))vals.push(r.mcdP);if(valid(r.spP))vals.push(r.spP)});let lo=Math.floor(Math.min(...vals)/5)*5,hi=Math.ceil(Math.max(...vals)/5)*5;if(lo===hi)hi=lo+5;const w=700,h=330,L=72,R=18,T=18,B=48,rg=hi-lo,x=i=>L+(w-L-R)*i/(rr.length-1),y=v=>T+(h-T-B)*(1-(v-lo)/rg);let s='';for(let i=0;i<5;i++){const v=hi-rg*i/4,Y=y(v);s+=`<line class="grid-line" x1="${L}" y1="${Y}" x2="${w-R}" y2="${Y}"/><text class="axis-label" text-anchor="end" x="${L-9}" y="${Y+5}">${v>0?'+':''}${Math.round(v)}%</text>`}s+=`<polyline class="chart-line" points="${rr.map((r,i)=>x(i)+','+y(r.mcdP)).join(' ')}"/><polyline class="sp-line" points="${rr.map((r,i)=>valid(r.spP)?x(i)+','+y(r.spP):'').filter(Boolean).join(' ')}"/>`;addXAxis(rr,x,h,s2=>s+=s2);markers.forEach(m=>{const i=rr.findIndex(r=>r.date===m.date);if(i>=0){const X=x(i),Y=y(rr[i].mcdP);s+=`<line class="buy-line" x1="${X}" y1="${T}" x2="${X}" y2="${h-B}"/><circle class="buy-point" cx="${X}" cy="${Y}" r="7"/>`}});svg.innerHTML=s}
function drawLine(id,rows,key,markers=[],lineClass='chart-line'){const svg=$(id);if(!svg||rows.length<2){if(svg)svg.innerHTML='';return}const w=700,h=id==='priceChart'?330:250,L=72,R=18,T=18,B=42,vals=rows.map(r=>N(r[key])).filter(Number.isFinite),min0=Math.min(...vals),max0=Math.max(...vals),pad=(max0-min0||Math.abs(max0)||1)*.08,min=min0-pad,max=max0+pad,rg=max-min||1,x=i=>L+(w-L-R)*i/(rows.length-1),y=v=>T+(h-T-B)*(1-(N(v)-min)/rg);let html='';for(let i=0;i<4;i++){const v=max-rg*i/3,Y=T+(h-T-B)*i/3;html+=`<line class="grid-line" x1="${L}" y1="${Y}" x2="${w-R}" y2="${Y}"/><text class="axis-label" text-anchor="end" x="${L-9}" y="${Y+5}">${axisValue(key,v)}</text>`}html+=`<polyline class="${lineClass}" points="${rows.map((r,i)=>x(i)+','+y(r[key])).join(' ')}"/>`;addXAxis(rows,x,h,s=>html+=s);markers.forEach(m=>{const i=rows.findIndex(r=>r.date===m.date);if(i>=0){const X=x(i),Y=y(rows[i][key]);html+=`<line class="buy-line" x1="${X}" y1="${T}" x2="${X}" y2="${h-B}"/><circle class="buy-point" cx="${X}" cy="${Y}" r="7"/><text class="buy-label" x="${Math.min(X+9,w-90)}" y="${Math.max(Y-12,25)}">Kjøp</text>`}});svg.innerHTML=html}
function addXAxis(rows,x,h,add){const idx=[0,Math.round((rows.length-1)*.25),Math.round((rows.length-1)*.5),Math.round((rows.length-1)*.75),rows.length-1];idx.forEach((n,i)=>add(`<text class="axis-label" text-anchor="${i===0?'start':i===4?'end':'middle'}" x="${x(n)}" y="${h-8}">${shortDate(rows[n].date)}</text>`))}
function drawBars(id,rows,key){const svg=$(id);if(!svg||!rows.length){if(svg)svg.innerHTML='';return}const w=700,h=300,L=70,R=18,T=72,B=48,vals=rows.map(r=>N(r[key])).filter(Number.isFinite),max0=Math.max(...vals),min0=Math.min(0,...vals),pad=(max0-min0||1)*.10,max=max0+pad,min=min0,rg=max-min||1,plotH=h-T-B,gap=(w-L-R)/rows.length,bw=gap*.58;let html='';for(let i=0;i<4;i++){const v=max-rg*i/3,Y=T+plotH*i/3;html+=`<line class="grid-line" x1="${L}" y1="${Y}" x2="${w-R}" y2="${Y}"/><text class="axis-label" text-anchor="end" x="${L-9}" y="${Y+5}">${barValue(key,v)}</text>`}rows.forEach((r,i)=>{const v=N(r[key]),baseY=T+plotH*(max-0)/rg,y=T+plotH*(max-v)/rg,bh=Math.abs(baseY-y),x=L+i*gap+(gap-bw)/2,topY=Math.min(y,baseY),yearAgo=findYearAgo((DATA?.financials?.incomeMCD||[]),r.period);let ch=null;if(yearAgo&&valid(yearAgo[key])&&N(yearAgo[key])!==0){ch=key==='operatingMargin'?N(r[key])-N(yearAgo[key]):N(r[key])/N(yearAgo[key])-1}html+=`<rect x="${x}" y="${topY}" width="${bw}" height="${Math.max(bh,2)}" rx="7" fill="rgba(112,88,120,.70)"/><text class="bar-value" text-anchor="middle" x="${x+bw/2}" y="${Math.max(topY-28,31)}">${barValue(key,v)}</text>`;if(valid(ch)){const txt=key==='operatingMargin'?`${ch>=0?'▲':'▼'} ${num(Math.abs(ch)*100,1)} pp`:`${ch>=0?'▲':'▼'} ${pct(Math.abs(ch))}`;html+=`<text class="bar-change ${ch>=0?'svg-positive':'svg-negative'}" text-anchor="middle" x="${x+bw/2}" y="${Math.max(topY-10,50)}">${txt}</text>`}html+=`<text class="axis-label" text-anchor="middle" x="${x+bw/2}" y="${h-13}">${r.period.replace(' 20','’')}</text>`});svg.innerHTML=html}
function barValue(key,v){if(key==='revenue')return '$'+num(v/1000,1)+' mrd';if(key==='eps')return '$'+num(v,2);if(key==='operatingMargin')return num(v*100,1)+'%';return num(v,1)}
function axisValue(key,v){if(key==='mcdUSD')return '$'+Math.round(v);if(key==='usdNok')return num(v,2);if(key==='peTtm')return num(v,1)+'×';return num(v,1)}
function shortDate(s){const d=new Date(String(s).slice(0,10)+'T12:00:00');return isNaN(d)?String(s):new Intl.DateTimeFormat('nb-NO',{month:'short',year:'2-digit'}).format(d)}
function formatDate(s){if(!s)return'–';const d=new Date(String(s).slice(0,10)+'T12:00:00');return isNaN(d)?String(s):new Intl.DateTimeFormat('nb-NO',{day:'2-digit',month:'short',year:'numeric'}).format(d)}
function formatDateTime(s){if(!s)return'–';const d=new Date(s);return isNaN(d)?String(s):new Intl.DateTimeFormat('nb-NO',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(d)}
init();
